# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            SOC 401 DS/AI LAB
tagline:          ''
description:      'Creating a website with github.' 
url:              "https://alwu25.github.io"
baseurl:          "/My-SOC-401-Project/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/alwu25/My-SOC-401-Project/
